name: Publish VS Code Extension

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags like v0.1.0

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Updated to Node 20
          cache: 'npm'

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Install vsce globally
        run: npm install -g @vscode/vsce@latest

      - name: Build extension
        run: npm run vscode:prepublish

      - name: Publish to Visual Studio Marketplace
        run: vsce publish -p $VSCE_PAT
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
